Prevent against micros() overflowing in refreshDisplay
DeanIsMe/SevSeg pull request #88
Opened 2021-05-03 21:17 UTC by tagry

Hello,
I have experienced an issue when I don't call refreshDisplay for a while. This issue is caused by a bad timing and an overflow on the function micros() which happens every 70 minutes. This makes prevUpdateTime > us and (int32_t)(us - prevUpdateTime) < waitOffTime could take up to 70 minutes to be false again.
Please merge this PR if you like the fix. 
Best,
Tom

2021-05-04 04:47 UTC, DeanIsMe commented
I don't understand how this occurs. As the subtraction is performed with 32-bit numbers, the overflow should not make a difference. Here's some quick code which demonstrates that when the overflow of micros() occurs, the check `((int32_t)(us - prevUpdateTime) < waitOffTime)` will still operate as expected.
https://onlinegdb.com/BkRLZ8ADd
What compiler and board are you using?

2021-05-04 07:15 UTC, tagry commented
> I don't understand how this occurs. As the subtraction is performed with 32-bit numbers, the overflow should not make a difference. Here's some quick code which demonstrates that when the overflow of micros() occurs, the check `((int32_t)(us - prevUpdateTime) < waitOffTime)` will still operate as expected.
> https://onlinegdb.com/BkRLZ8ADd
> What compiler and board are you using?

Hello,
This is working only if you overflow the subtraction. If us is big you will get a negative number. Finally the solution is simpler than expected. I just removed the cast to keep the unsigned. 
Here the code to make you understand: https://onlinegdb.com/Hk9uNuRDd

2021-05-05 03:26 UTC, DeanIsMe commented
Ahh I see - so this could only occur if refreshDisplay has not been run for 35-70 minutes (or 105-140 minutes, or 175-210 minutes, etc).

2021-05-05 03:29 UTC, DeanIsMe requested changes
A very neat fix. The only slight issue: some compilers might spit out a warning that we're comparing signed to unsigned values. So, waitOffTime and ledOnTime should probably be changed to unsigned values.

2021-05-05 07:25 UTC, tagry commented
Good point ! Change has been done. 
Thanks for your support !

2021-05-06 03:45 UTC, merged

2021-05-06 03:45 UTC, DeanIsMe commented
Merged. Thank you!